### ISSUE TITLE
Pagination children styling

### ISSUE THREAD

**Issue by larsvanpoucke** [a-ui/acpaas_branding_scss#8]
Can you add a `.m-pagination__button` or `.m-pagination__page` class that contains the styling of the child elements of the pagination molecule?

Should be something like this:
```
<ul class="m-pagination">
  <li class="m-pagination__button">1</li>
  <li class="m-pagination__button">2</li>
  <li class="m-pagination__button">3</li>
  <li class="m-pagination__button m-pagination__button--disabled">...</li>
</ul>
```

Now the styling is applied to a specific dom element (li-tag) (see screenshot http://prntscr.com/kroq6i ) which is not very reusable / flexible.

**Comment by e2o** [comment]
Issue is regarding this file:
https://github.com/a-ui/core_branding_scss/blob/master/src/styles/molecules/_molecules.pagination.scss

(so I think this issue is on the wrong repo)

Styling selectors should be classnames instead of `<a>-tag`.
That way we can also use stuff like `<button>` as a pagination-element.
